### PR TITLE
Development

### PR DESCRIPTION
**Pull request by leticiaseixas**
Creating a PR to the development branch to generate a preview for future developments.

### CODE REVIEW

**Comment by leticiaseixas** [comment]
Changelog (08 September 2022):

- Add new filter and form field to distinguish individual wanting training vs. training for an organization #302
- Modified order of Type of resource filter and form field options #303
- Combined Graduate program and Undergraduate program filters #303
- New text box to promote W3Cx accessibility course #317
- Add scope info to submission form #321

**Comment by shawna-slh** [comment]
+1

**Comment by vmmiller** [comment]
+1

**Comment by AndrewArch** [comment]
+1

**Comment by hkramer** [comment]
+1

**Comment by iadawn** [comment]
+1  to most... some concerns with scope info. See https://github.com/w3c/wai-course-list/issues/321#issuecomment-1241741448

**Comment by carlosapaduarte** [comment]
+1

**Comment by lakeen** [comment]
+1

**Comment by Sylvie42** [comment]
+1

**Comment by MicheleAWilliams-A11y** [comment]
+1

**Pull request merged**
